<?php

/**
 * @file
 * Hp_alumni_featured module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_alumni_featured_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_alumni_featured':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   This sets variables for getting events, and then gets events.
 */
function hp_alumni_featured_preprocess_paragraph__hp_alumni_featured(&$variables) {

  // Unique Cache ID.
  $uuid = $variables['elements']['#paragraph']->uuid->value;
  $cid = 'hp_alumni_featured--' . $uuid;

  // Check on env to get events from.
  $env = $variables['elements']['#paragraph']->field_hp_pf_environment->value;
  $env_url = 'https://thedig.howard.edu';
  if ($env == 'stg') {
    $env_url = 'http://stg.thedig.howard.edu';
  }
  elseif ($env == 'dev') {
    $env_url = 'http://dev.thedig.howard.edu';
  }
  $variables['hp_aft_env_url'] = $env_url;

  // Get profiles.
  $feat_alumni = $variables['elements']['#paragraph']->get('field_hp_aft_chosen_alumni')->getValue();

  //$variables['hp_aft_profiles'] = _hp_alumni_featured_get_profiles($env_url, $feat_alumni, $cid);
  $variables['hp_aft_profiles'] = \Drupal::service('howard.news')->getPeople($env_url, $feat_alumni, NULL, NULL, 50, $uuid);

}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_alumni_featured_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_alumni_featured' => [
      'base hook' => 'paragraph',
    ],
  ];
}
