<?php

/**
 * @file
 * Ip_button_link module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_video_slideshow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_video_slideshow':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 */
function hp_video_slideshow_preprocess_paragraph__hp_video_slide(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];

  // Get video URL.
  if ($paragraph->hasField('field_hp_vs_video_url')) {
    $variables['hp_vs_video_url'] = $paragraph->get('field_hp_vs_video_url')->first()->getUrl();
  }
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_video_slideshow_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_video_slideshow' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__hp_video_slide' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Updates to allow optional link title.
 */
function hp_video_slideshow_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hp_video_slideshow');
}
