<?php

/**
 * @file
 * Hp_countdown module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Datetime\DrupalDateTime;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_countdown_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.hp_countdown':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      } else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   This sets variables for getting events, and then gets events.
 */
function hp_countdown_preprocess_paragraph__hp_countdown(&$variables)
{

  // Format Date Field.
  $datetime = new DrupalDateTime($variables['elements']['#paragraph']->field_hp_cdn_date->value, 'UTC');
  $date_formatter = \Drupal::service('date.formatter');
  $variables['hp_cdn_ymd'] = $date_formatter->format($datetime->getTimestamp(), 'custom', 'Y-m-d');
  $variables['hp_cdn_hms'] = $date_formatter->format($datetime->getTimestamp(), 'custom', 'H:i:s');

}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_countdown_theme($existing, $type, $theme, $path)
{
  return [
    'paragraph__hp_countdown' => [
      'base hook' => 'paragraph',
    ],
  ];
}
