<?php

/**
 * @file
 * hp_profiles_feed_by_id module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_profiles_feed_by_id_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_profiles_feed_by_id':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   This sets variables for getting events, and then gets events.
 */
function hp_profiles_feed_by_id_preprocess_paragraph__hp_profiles_feed_by_id(&$variables) {

  // Unique Cache ID.
  $uuid = $variables['elements']['#paragraph']->uuid->value;
  $cid = 'hp_profiles_feed_by_id--' . $uuid;

  // Environment URL.
  $env_url = 'https://profiles.howard.edu';
  $variables['hp_pf_env_url'] = $env_url;
  $sort = 'all';
  $department = NULL;
  $admin_taxonomy = NULL;

  

  if (isset($variables['elements']['#paragraph']->field_hp_pfid_profiles_dept->value)) {
    $department = $variables['elements']['#paragraph']->field_hp_pfid_profiles_dept->value;
    // Decode string workaround due to bug in core or external_data_source.
    $department = str_replace('id=', '', $department);
  }

  // Get profile ID's.
  $selected_profiles = $variables['elements']['#paragraph']->get('field_hp_pfid_selected_profiles')->getValue();
  $nids = array_map(fn($item) => $item['value'], $selected_profiles);

  // Get all profiles from HU profiles.
  $raw_profiles = \Drupal::service('howard.profiles')->getProfiles($env_url, $sort, $department, $cid, $admin_taxonomy, $nids);
  $raw_profiles_indexed = [];
  foreach ($raw_profiles['data'] as $item) {
      $raw_profiles_indexed[$item['nid']] = $item;
  }
  $ordered_profiles = ['data' => []];
  foreach ($nids as $nid) {
      if (isset($raw_profiles_indexed[$nid])) {
          $ordered_profiles['data'][] = $raw_profiles_indexed[$nid];
      }
  }
  // Set the variable to be the reordered array.
  $variables['hp_pfid_profiles'] = $ordered_profiles;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_profiles_feed_by_id_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_profiles_feed_by_id' => [
      'base hook' => 'paragraph',
    ],
  ];
}


function hp_profiles_feed_by_id_uninstall() {
  // Paragraph type.
  \Drupal::configFactory()->getEditable('paragraphs.paragraphs_type.hp_profiles_feed_by_id')->delete();

  // Field instances.
  \Drupal::configFactory()->getEditable('field.field.paragraph.hp_profiles_feed_by_id.field_hp_pfid_descriptive_text')->delete();
  \Drupal::configFactory()->getEditable('field.field.paragraph.hp_profiles_feed_by_id.field_hp_pfid_profiles_dept')->delete();
  \Drupal::configFactory()->getEditable('field.field.paragraph.hp_profiles_feed_by_id.field_hp_pfid_selected_profiles')->delete();
  \Drupal::configFactory()->getEditable('field.field.paragraph.hp_profiles_feed_by_id.field_hp_pfid_title')->delete();

  // Field storage.
  \Drupal::configFactory()->getEditable('field.storage.paragraph.field_hp_pfid_descriptive_text')->delete();
  \Drupal::configFactory()->getEditable('field.storage.paragraph.field_hp_pfid_profiles_dept')->delete();
  \Drupal::configFactory()->getEditable('field.storage.paragraph.field_hp_pfid_selected_profiles')->delete();
  \Drupal::configFactory()->getEditable('field.storage.paragraph.field_hp_pfid_title')->delete();

  // Form display.
  \Drupal::configFactory()->getEditable('core.entity_form_display.paragraph.hp_profiles_feed_by_id.default')->delete();

  // View display.
  \Drupal::configFactory()->getEditable('core.entity_view_display.paragraph.hp_profiles_feed_by_id.default')->delete();
}