<?php

/**
 * @file
 * Howard Paragraphs AI Agent Embed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_ai_agent_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_ai_agent_embed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_ai_agent_embed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_ai_agent' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 * Attach AI Agent library to paragraphs.
 */
function hp_ai_agent_embed_entity_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, $view_mode) {
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() === 'hp_ai_agent') {
    $build['#attached']['library'][] = 'hp_ai_agent_embed/ai-agent-embed';
  }
}
