<?php

/**
 * @file
 * hp_parallax module file.
 */

 use Drupal\Core\Routing\RouteMatchInterface;
 use Drupal\paragraphs\Entity\Paragraph;

 /**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_parallax_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_parallax':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

 /**
  * Implements hook_theme().
  * Lets us define our paragraphs templates in this module.
  */
 function hp_parallax_theme($existing, $type, $theme, $path) {
   return [
     'paragraph__hp_parallax' => [
       'base hook' => 'paragraph',
     ]
   ];
 }

 function hp_parallax_preprocess_maintenance_page(&$variables) {
  $variables['#attached']['library'][] =  'hp_parallax/global-styling';
}


