<?php

/**
 * @file
 * Ip_button_link module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\media\Entity\Media;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_testimonial_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_testimonial':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   This sets a url for the image.
 */
function hp_testimonial_preprocess_paragraph__hp_testimonial(&$variables) {
  $paragraph = $variables['elements']['#paragraph'];
  // Get media image URL.
  if ($paragraph->hasField('field_hp_tst_image')) {
    $bkrd_image = $paragraph->get('field_hp_tst_image')->getValue();
    if ($bkrd_image && !empty($bkrd_image)) {
      $entity = Media::load($bkrd_image[0]['target_id']);
      if (isset($entity->field_media_image->entity)) {
        $variables['hp_tst_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($entity->field_media_image->entity->getFileUri());
      }
    }
  }
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_testimonial_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_testimonial' => [
      'base hook' => 'paragraph',
    ],
  ];
}
