<?php

/**
 * @file
 * Ip_views_embed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_views_embed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_views_embed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 * Lets us define our paragraphs templates in this module.
 */
function hp_views_embed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__ip_views_embed' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_ve_view' => [
      'base hook' => 'paragraph',
    ],
    'field__paragraph__field_ip_ve_title' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * Implements hook_field_WIDGET_TYPE_paragraphs_form_alter().
 *
 * Adds helper text to the paragraph. May need to switch to hp_views_embed_field_widget_paragraphs_form_alter in the future.
 */
function hp_views_embed_field_widget_entity_reference_paragraphs_form_alter(&$element, &$form_state, $context) {
  if ($element['#paragraph_type'] == 'ip_views_embed') {
    // Tips text from idfive.
    $markup .= '<p>This widget is primarily designed for administrators to add specially crafted views, mainly as overview, and search pages. These should not be modified or changed without express knowledge of what these views do, how they work, and why they are there.</p>';
    $markup .= '<p><a target="_blank" href="/admin/help/hp_views_embed">Views Embed Help</a></p>';
    $element['ip_views_embed_tips'] = [
      '#type' => 'fieldset',
      '#title' => t('HP Views Embed: ADMINISTRATOR USE ONLY'),
      '#weight' => -1000,
    ];
    $element['ip_views_embed_tips']['#markup'] = $markup;
  }
}
