<?php

/**
 * @file
 * Hp_deadline_feed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_deadline_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_deadline_feed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * This sets variables for getting events, and then gets events.
 */
function hp_deadline_feed_preprocess_paragraph__hp_deadline_feed(&$variables) {
  // UUID to pass for cache.
  $uuid = $variables['elements']['#paragraph']->uuid->value;

  // Check on env to get events from.
  $env = $variables['elements']['#paragraph']->field_hp_df_environment->value;
  $env_url = 'https://calendar.howard.edu';
  if ($env == 'stg') {
    $env_url = 'http://stg.calendar.howard.edu';
  }
  elseif ($env == 'dev') {
    $env_url = 'http://dev.calendar.howard.edu';
  }

  // Result count.
  $result_count_chosen = $variables['elements']['#paragraph']->field_hp_df_number_to_disp->value;
  $result_count = 50;
  if (isset($result_count_chosen)) {
    $result_count = $result_count_chosen;
  }

  // Hide time in deadline.
  $hide_time_chosen = $variables['elements']['#paragraph']->field_hp_df_hide_time->value;
  $hide_time = FALSE;
  if ($hide_time_chosen == TRUE) {
    $hide_time = TRUE;
  }
  $variables['hp_df_hide_time'] = $hide_time;

  // Hide Schools/colleges column.
  $hide_sc_chosen = $variables['elements']['#paragraph']->field_hp_df_hide_schools->value;
  $hide_sc = FALSE;
  if ($hide_sc_chosen == TRUE) {
    $hide_sc = TRUE;
  }
  $variables['hp_df_hide_schools'] = $hide_sc;

  // Hide Department / Admin column.
  $hide_da_chosen = $variables['elements']['#paragraph']->field_hp_df_hide_admin->value;
  $hide_da = FALSE;
  if ($hide_da_chosen == TRUE) {
    $hide_da = TRUE;
  }
  $variables['hp_df_hide_admin'] = $hide_da;

  // Check on admin categories filter.
  $admin_category = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_df_dl_admin_category->value)) {
    $admin_category = $variables['elements']['#paragraph']->field_hp_df_dl_admin_category->value;
    // Decode string workaround due to bug in core or external_data_source.
    $admin_category = str_replace('id=', '', $admin_category);
  }

  // Check on Schools and Colleges filter.
  $schools_colleges = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_df_dl_schools_colleg->value)) {
    $schools_colleges = $variables['elements']['#paragraph']->field_hp_df_dl_schools_colleg->value;
    // Decode string workaround due to bug in core or external_data_source.
    $schools_colleges = str_replace('id=', '', $schools_colleges);
  }

  // Get deadlines.
  $variables['hp_df_deadlines'] = _hp_deadline_feed_get_deadlines($env_url, $admin_category, $schools_colleges, $result_count, 1, $uuid);

}

/**
 * Implements hook_theme().
 *
 * Let's us define our paragraphs templates in this module.
 */
function hp_deadline_feed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_deadline_feed' => [
      'base hook' => 'paragraph',
    ],
  ];
}

/**
 * CUSTOM FUNCTIONS.
 */

/**
 * Gets deadlines from calendar, and displays.
 */
function _hp_deadline_feed_get_deadlines($env_url = 'https://calendar.howard.edu', $admin_category = NULL, $schools_colleges = NULL, $range = 50, $page = 1, $id = 'default') {
  if ($cache = \Drupal::cache()->get('hp_deadline_feed--' . $id)) {
    return $cache->data;
  }
  else {
    $d = new DateTime('+1day');
    $tomorrow = $d->format('Y-m-d');

    $url = $env_url . "/api/deadlines/?sort=date&fields=label,date,deadline_link,college_school,admin_department&range=" . $range . "&page=" . $page . "&filter[date][value][0]=" . $tomorrow . "%2016:00:00&filter[date][operator][0]='>'";
    if (isset($admin_category)) {
      $url .= "&filter[admin_department][value][0]=" . $admin_category . "&filter[admin_department][operator][0]='IN'";
    }
    if (isset($schools_colleges)) {
      $url .= "&filter[college_school][value][0]=" . $schools_colleges . "&filter[college_school][operator][0]='IN'";
    }
    $result = file_get_contents($url);
    $result = json_decode($result, TRUE);
    $result = $result['data'];
    if ($result) {
      \Drupal::cache()->set('hp_deadline_feed--' . $id, $result, time() + 7200);
      return $result;
    }
    else {
      return NULL;
    }
  }
}
