<?php

/**
 * @file
 * hp_programs_feed module file.
 */

 use Drupal\Core\Routing\RouteMatchInterface;
 use Drupal\paragraphs\Entity\Paragraph;
 use Drupal\Core\Form\FormStateInterface;

 /**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_programs_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_programs_feed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 * @param $variables
 * This sets variables for getting events, and then gets events.
 */
function hp_programs_feed_preprocess_paragraph__hp_programs_feed(&$variables) {
  // UUID to pass for cache
  $uuid = $variables['elements']['#paragraph']->uuid->value;

  // Check on env to get events from
  $env = $variables['elements']['#paragraph']->field_hp_nf_environment->value;
  $env_url = 'https://programs.howard.edu';
  if($env == 'stg') {
    $env_url = 'http://stg.programs.howard.edu';
  } elseif($env == 'dev') {
    $env_url = 'http://dev.programs.howard.edu';
  }
  $variables['hp_pgf_env_url'] = $env_url;

  // Check on Degree Classifications filter
  $degree_classification = null;
  if(isset($variables['elements']['#paragraph']->field_hp_pgf_degree_classificati->value)) {
    $degree_classification = $variables['elements']['#paragraph']->field_hp_pgf_degree_classificati->value;
    // Decode string workaround due to bug in core or external_data_source
    $degree_classification = str_replace('id=','',$degree_classification);
  }

  // Check on admin categories filter
  $department = null;
  if(isset($variables['elements']['#paragraph']->field_hp_pgf_program_admin_category->value)) {
    $department = $variables['elements']['#paragraph']->field_hp_pgf_program_admin_category->value;
    // Decode string workaround due to bug in core or external_data_source
    $department = str_replace('id=','',$department);
  }

  // Get programs
  $variables['hp_nf_news'] = _hp_programs_feed_get_programs($env_url, $school, $department, 3, 1, $uuid);
  

}

 /**
  * Implements hook_theme().
  * Lets us define our paragraphs templates in this module.
  */
 function hp_programs_feed_theme($existing, $type, $theme, $path) {
   return [
     'paragraph__hp_programs_feed' => [
       'base hook' => 'paragraph',
     ]
   ];
 }


/**
* CUSTOM FUNCTIONS
*
*/


 /**
 * Gets programs from programs.howard.edu, and displays.
 *
 */
 function _hp_programs_feed_get_programs($env_url = 'https://programs.howard.edu', $school = null, $department = null, $range = 3, $page = 1, $id = 'default') {
   if ($cache = \Drupal::cache()->get('hp_news_feed--' . $id . '-' . $range)) {
     return $cache->data;
   }
   else {
     $currentDate = date('Y-m-d');
     $url = $env_url . "/api/articlesearch/%20?sort=-publication_date&fields=id,label,publication_date_formatted,image,uri,summary&range=" . $range . "&page=" . $page . "&filter[publication_date][value][]=" . $currentDate . "%2023:59:59&filter[publication_date][operator]='<='&filter[exclude_from_main_feed][value]=1&filter[exclude_from_main_feed][operator]='!='";
     if(isset($category)) {
       $url .= "&filter[taxonomy_3][value][]=" . $school;
     }
     if(isset($admin_category)) {
       $url .= "&filter[taxonomy_5][value][]=" . $department;
     }
     $result = file_get_contents($url);
     $result = json_decode($result, true);
     $result = $result['data'];
     if($result) {
       \Drupal::cache()->set('hp_news_feed--' . $id. '-' . $range, $result, time() + 7200);
       return $result;
     } else {
       return null;
     }
   }
 }
