<?php

/**
 * @file
 * Hp_programs_feed module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function hp_programs_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.hp_programs_feed':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_preprocess_paragraph().
 *
 * @param $variables
 *   This sets variables for getting events, and which are then passed to JS.
 */
function hp_programs_feed_preprocess_paragraph__hp_programs_feed(&$variables) {

  // Check on env to get events from.
  $env = 'prod';
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_environment->value)) {
    $env = $variables['elements']['#paragraph']->field_hp_pgf_environment->value;
  }
  $variables['hp_pgf_env_url'] = $env;

  // Check on Degree Classifications filter.
  $degree_classification = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_degree_classificati->value)) {
    $degree_classification = $variables['elements']['#paragraph']->field_hp_pgf_degree_classificati->value;
    // Decode string workaround due to bug in core or external_data_source.
    $degree_classification = str_replace('id=', '', $degree_classification);
  }
  $variables['hp_pgf_degree'] = $degree_classification;

  // Check on schools filter.
  $school = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_school->value)) {
    $school = $variables['elements']['#paragraph']->field_hp_pgf_school->value;
    // Decode string workaround due to bug in core or external_data_source.
    $school = str_replace('id=', '', $school);
  }
  $variables['hp_pgf_school'] = $school;

  // Check on subject filter.
  $subject = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_subject->value)) {
    $subject = $variables['elements']['#paragraph']->field_hp_pgf_subject->value;
    // Decode string workaround due to bug in core or external_data_source.
    $subject = str_replace('id=', '', $subject);
  }
  $variables['hp_pgf_subject'] = $subject;

  // Check on profession filter.
  $profession = NULL;
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_profession->value)) {
    $profession = $variables['elements']['#paragraph']->field_hp_pgf_profession->value;
    // Decode string workaround due to bug in core or external_data_source.
    $profession = str_replace('id=', '', $profession);
  }
  $variables['hp_pgf_profession'] = $profession;

  // Degree Filter
  $show_degree_filter = 'false';
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_show_degree_filter->value) && $variables['elements']['#paragraph']->field_hp_pgf_show_degree_filter->value == 1) {
    $show_degree_filter = 'true';
  }
  $variables['hp_pgf_show_degree_filter'] = $show_degree_filter;

  // School Filter
  $show_school_filter = 'false';
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_show_school_filter->value) && $variables['elements']['#paragraph']->field_hp_pgf_show_school_filter->value == 1) {
    $show_school_filter = 'true';
  }
  $variables['hp_pgf_show_school_filter'] = $show_school_filter;

  // Subject Filter
  $show_subject_filter = 'false';
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_show_subject_filter->value) && $variables['elements']['#paragraph']->field_hp_pgf_show_subject_filter->value == 1) {
    $show_subject_filter = 'true';
  }
  $variables['hp_pgf_show_subject_filter'] = $show_subject_filter;

  // Related Profession Filter
  $show_profession_filter = 'false';
  if (isset($variables['elements']['#paragraph']->field_hp_pgf_show_prof_filter->value) && $variables['elements']['#paragraph']->field_hp_pgf_show_prof_filter->value == 1) {
    $show_profession_filter = 'true';
  }
  $variables['hp_pgf_show_profession_filter'] = $show_profession_filter;

}

/**
 * Implements hook_theme().
 *
 * Lets us define our paragraphs templates in this module.
 */
function hp_programs_feed_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__hp_programs_feed' => [
      'base hook' => 'paragraph',
    ],
  ];
}


// UPDATES

/**
 * Updates to allow unlimited showing/hiding filters.
 */
function hp_programs_feed_update_8001() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hp_programs_feed');
}

/**
 * Updates to allow related professions.
 */
function hp_programs_feed_update_8002() {
  \Drupal::service('config.installer')->installDefaultConfig('module', 'hp_programs_feed');
}
